AllCops:
  Exclude:
    - features/**/*
    - db/**/*
    - bundle_bin/**/*
  Include:
    - damerau-levenshtein.gemspec
  TargetRubyVersion: ">=2.5"
Metrics/ModuleLength:
  Max: 1000
Style/StringLiterals:
  EnforcedStyle: double_quotes
Layout/DotPosition:
  EnforcedStyle: trailing
Naming/FileName:
  Enabled: false
